baseurl = "https://www.ebackman.net"
languageCode = "en-us"
theme = "m10c"
title = "ebackman.net"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 1

[params]
author = "Erik Bäckman"
avatar = "images/avatar.png"
description = "My thoughts on programming, emacs and more"

[params.style]
  darkestColor = "#111213"
  darkColor = "#1D1F20"
  primaryColor = "#907ACD"
  lightColor = "#DFE0E2"
  lightestColor = "#fff"

[[params.social]]
  name = "github"
  url = "https://github.com/erikbackman"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/ThisIsErik"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/erba"
